// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CharacterDef {
    pub id: u32,
    pub identity: __sdk::Identity,
    pub name: String,
    pub transform_id: u32,
    pub class_id: u32,
    pub race_id: u32,
    pub health_id: u32,
    pub mana_id: u32,
}

impl __sdk::InModule for CharacterDef {
    type Module = super::RemoteModule;
}
