// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::character_def_type::CharacterDef;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `character_def`.
///
/// Obtain a handle from the [`CharacterDefTableAccess::character_def`] method on [`super::RemoteTables`],
/// like `ctx.db.character_def()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_def().on_insert(...)`.
pub struct CharacterDefTableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterDef>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `character_def`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CharacterDefTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CharacterDefTableHandle`], which mediates access to the table `character_def`.
    fn character_def(&self) -> CharacterDefTableHandle<'_>;
}

impl CharacterDefTableAccess for super::RemoteTables {
    fn character_def(&self) -> CharacterDefTableHandle<'_> {
        CharacterDefTableHandle {
            imp: self.imp.get_table::<CharacterDef>("character_def"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CharacterDefInsertCallbackId(__sdk::CallbackId);
pub struct CharacterDefDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CharacterDefTableHandle<'ctx> {
    type Row = CharacterDef;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterDef> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CharacterDefInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterDefInsertCallbackId {
        CharacterDefInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CharacterDefInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CharacterDefDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterDefDeleteCallbackId {
        CharacterDefDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CharacterDefDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CharacterDef>("character_def");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct CharacterDefUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CharacterDefTableHandle<'ctx> {
    type UpdateCallbackId = CharacterDefUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CharacterDefUpdateCallbackId {
        CharacterDefUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CharacterDefUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<CharacterDef>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterDef>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `character_def`,
/// which allows point queries on the field of the same name
/// via the [`CharacterDefIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_def().id().find(...)`.
pub struct CharacterDefIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CharacterDef, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CharacterDefTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `character_def`.
    pub fn id(&self) -> CharacterDefIdUnique<'ctx> {
        CharacterDefIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CharacterDefIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<CharacterDef> {
        self.imp.find(col_val)
    }
}
