// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::character_pawn_type::CharacterPawn;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `character_pawn`.
///
/// Obtain a handle from the [`CharacterPawnTableAccess::character_pawn`] method on [`super::RemoteTables`],
/// like `ctx.db.character_pawn()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_pawn().on_insert(...)`.
pub struct CharacterPawnTableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterPawn>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `character_pawn`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CharacterPawnTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CharacterPawnTableHandle`], which mediates access to the table `character_pawn`.
    fn character_pawn(&self) -> CharacterPawnTableHandle<'_>;
}

impl CharacterPawnTableAccess for super::RemoteTables {
    fn character_pawn(&self) -> CharacterPawnTableHandle<'_> {
        CharacterPawnTableHandle {
            imp: self.imp.get_table::<CharacterPawn>("character_pawn"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CharacterPawnInsertCallbackId(__sdk::CallbackId);
pub struct CharacterPawnDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CharacterPawnTableHandle<'ctx> {
    type Row = CharacterPawn;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterPawn> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CharacterPawnInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterPawnInsertCallbackId {
        CharacterPawnInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CharacterPawnInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CharacterPawnDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterPawnDeleteCallbackId {
        CharacterPawnDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CharacterPawnDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CharacterPawn>("character_pawn");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}
pub struct CharacterPawnUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CharacterPawnTableHandle<'ctx> {
    type UpdateCallbackId = CharacterPawnUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CharacterPawnUpdateCallbackId {
        CharacterPawnUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CharacterPawnUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<CharacterPawn>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterPawn>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `character_pawn`,
/// which allows point queries on the field of the same name
/// via the [`CharacterPawnIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_pawn().id().find(...)`.
pub struct CharacterPawnIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CharacterPawn, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CharacterPawnTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `character_pawn`.
    pub fn id(&self) -> CharacterPawnIdUnique<'ctx> {
        CharacterPawnIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CharacterPawnIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<CharacterPawn> {
        self.imp.find(col_val)
    }
}

/// Access to the `identity` unique index on the table `character_pawn`,
/// which allows point queries on the field of the same name
/// via the [`CharacterPawnIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_pawn().identity().find(...)`.
pub struct CharacterPawnIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CharacterPawn, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CharacterPawnTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `character_pawn`.
    pub fn identity(&self) -> CharacterPawnIdentityUnique<'ctx> {
        CharacterPawnIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CharacterPawnIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<CharacterPawn> {
        self.imp.find(col_val)
    }
}
