// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::class_type::Class;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `class`.
///
/// Obtain a handle from the [`ClassTableAccess::class`] method on [`super::RemoteTables`],
/// like `ctx.db.class()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.class().on_insert(...)`.
pub struct ClassTableHandle<'ctx> {
    imp: __sdk::TableHandle<Class>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `class`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ClassTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ClassTableHandle`], which mediates access to the table `class`.
    fn class(&self) -> ClassTableHandle<'_>;
}

impl ClassTableAccess for super::RemoteTables {
    fn class(&self) -> ClassTableHandle<'_> {
        ClassTableHandle {
            imp: self.imp.get_table::<Class>("class"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ClassInsertCallbackId(__sdk::CallbackId);
pub struct ClassDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ClassTableHandle<'ctx> {
    type Row = Class;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Class> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ClassInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClassInsertCallbackId {
        ClassInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ClassInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ClassDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClassDeleteCallbackId {
        ClassDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ClassDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Class>("class");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}
pub struct ClassUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ClassTableHandle<'ctx> {
    type UpdateCallbackId = ClassUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ClassUpdateCallbackId {
        ClassUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ClassUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Class>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Class>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `class`,
/// which allows point queries on the field of the same name
/// via the [`ClassIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.class().id().find(...)`.
pub struct ClassIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Class, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ClassTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `class`.
    pub fn id(&self) -> ClassIdUnique<'ctx> {
        ClassIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ClassIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Class> {
        self.imp.find(col_val)
    }
}

/// Access to the `name` unique index on the table `class`,
/// which allows point queries on the field of the same name
/// via the [`ClassNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.class().name().find(...)`.
pub struct ClassNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Class, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ClassTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `class`.
    pub fn name(&self) -> ClassNameUnique<'ctx> {
        ClassNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ClassNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Class> {
        self.imp.find(col_val)
    }
}
