// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteCharacterArgs {
    pub character_id: u32,
}

impl From<DeleteCharacterArgs> for super::Reducer {
    fn from(args: DeleteCharacterArgs) -> Self {
        Self::DeleteCharacter {
            character_id: args.character_id,
        }
    }
}

impl __sdk::InModule for DeleteCharacterArgs {
    type Module = super::RemoteModule;
}

pub struct DeleteCharacterCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_character`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_character {
    /// Request that the remote module invoke the reducer `delete_character` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_delete_character`] callbacks.
    fn delete_character(&self, character_id: u32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `delete_character`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DeleteCharacterCallbackId`] can be passed to [`Self::remove_on_delete_character`]
    /// to cancel the callback.
    fn on_delete_character(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u32) + Send + 'static,
    ) -> DeleteCharacterCallbackId;
    /// Cancel a callback previously registered by [`Self::on_delete_character`],
    /// causing it not to run in the future.
    fn remove_on_delete_character(&self, callback: DeleteCharacterCallbackId);
}

impl delete_character for super::RemoteReducers {
    fn delete_character(&self, character_id: u32) -> __sdk::Result<()> {
        self.imp
            .call_reducer("delete_character", DeleteCharacterArgs { character_id })
    }
    fn on_delete_character(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u32) + Send + 'static,
    ) -> DeleteCharacterCallbackId {
        DeleteCharacterCallbackId(self.imp.on_reducer(
            "delete_character",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::DeleteCharacter { character_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, character_id)
            }),
        ))
    }
    fn remove_on_delete_character(&self, callback: DeleteCharacterCallbackId) {
        self.imp.remove_on_reducer("delete_character", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `delete_character`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_delete_character {
    /// Set the call-reducer flags for the reducer `delete_character` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn delete_character(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_delete_character for super::SetReducerFlags {
    fn delete_character(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("delete_character", flags);
    }
}
