// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::entity_movement_type::EntityMovement;
use super::move_intent_type::MoveIntent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `entity_movement`.
///
/// Obtain a handle from the [`EntityMovementTableAccess::entity_movement`] method on [`super::RemoteTables`],
/// like `ctx.db.entity_movement()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_movement().on_insert(...)`.
pub struct EntityMovementTableHandle<'ctx> {
    imp: __sdk::TableHandle<EntityMovement>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `entity_movement`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EntityMovementTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EntityMovementTableHandle`], which mediates access to the table `entity_movement`.
    fn entity_movement(&self) -> EntityMovementTableHandle<'_>;
}

impl EntityMovementTableAccess for super::RemoteTables {
    fn entity_movement(&self) -> EntityMovementTableHandle<'_> {
        EntityMovementTableHandle {
            imp: self.imp.get_table::<EntityMovement>("entity_movement"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EntityMovementInsertCallbackId(__sdk::CallbackId);
pub struct EntityMovementDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EntityMovementTableHandle<'ctx> {
    type Row = EntityMovement;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EntityMovement> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EntityMovementInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityMovementInsertCallbackId {
        EntityMovementInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EntityMovementInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EntityMovementDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityMovementDeleteCallbackId {
        EntityMovementDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EntityMovementDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EntityMovement>("entity_movement");
    _table.add_unique_constraint::<u32>("entity_id", |row| &row.entity_id);
}
pub struct EntityMovementUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EntityMovementTableHandle<'ctx> {
    type UpdateCallbackId = EntityMovementUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EntityMovementUpdateCallbackId {
        EntityMovementUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EntityMovementUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<EntityMovement>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EntityMovement>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `entity_id` unique index on the table `entity_movement`,
/// which allows point queries on the field of the same name
/// via the [`EntityMovementEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_movement().entity_id().find(...)`.
pub struct EntityMovementEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EntityMovement, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EntityMovementTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `entity_movement`.
    pub fn entity_id(&self) -> EntityMovementEntityIdUnique<'ctx> {
        EntityMovementEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EntityMovementEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<EntityMovement> {
        self.imp.find(col_val)
    }
}
