// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::mana_type::Mana;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `mana`.
///
/// Obtain a handle from the [`ManaTableAccess::mana`] method on [`super::RemoteTables`],
/// like `ctx.db.mana()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.mana().on_insert(...)`.
pub struct ManaTableHandle<'ctx> {
    imp: __sdk::TableHandle<Mana>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `mana`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ManaTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ManaTableHandle`], which mediates access to the table `mana`.
    fn mana(&self) -> ManaTableHandle<'_>;
}

impl ManaTableAccess for super::RemoteTables {
    fn mana(&self) -> ManaTableHandle<'_> {
        ManaTableHandle {
            imp: self.imp.get_table::<Mana>("mana"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ManaInsertCallbackId(__sdk::CallbackId);
pub struct ManaDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ManaTableHandle<'ctx> {
    type Row = Mana;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Mana> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ManaInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ManaInsertCallbackId {
        ManaInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ManaInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ManaDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ManaDeleteCallbackId {
        ManaDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ManaDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Mana>("mana");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct ManaUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ManaTableHandle<'ctx> {
    type UpdateCallbackId = ManaUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ManaUpdateCallbackId {
        ManaUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ManaUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Mana>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Mana>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `mana`,
/// which allows point queries on the field of the same name
/// via the [`ManaIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.mana().id().find(...)`.
pub struct ManaIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Mana, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ManaTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `mana`.
    pub fn id(&self) -> ManaIdUnique<'ctx> {
        ManaIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ManaIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Mana> {
        self.imp.find(col_val)
    }
}
