// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::movement_tick_timer_type::MovementTickTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MovementTickArgs {
    pub timer: MovementTickTimer,
}

impl From<MovementTickArgs> for super::Reducer {
    fn from(args: MovementTickArgs) -> Self {
        Self::MovementTick { timer: args.timer }
    }
}

impl __sdk::InModule for MovementTickArgs {
    type Module = super::RemoteModule;
}

pub struct MovementTickCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `movement_tick`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait movement_tick {
    /// Request that the remote module invoke the reducer `movement_tick` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_movement_tick`] callbacks.
    fn movement_tick(&self, timer: MovementTickTimer) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `movement_tick`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`MovementTickCallbackId`] can be passed to [`Self::remove_on_movement_tick`]
    /// to cancel the callback.
    fn on_movement_tick(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &MovementTickTimer) + Send + 'static,
    ) -> MovementTickCallbackId;
    /// Cancel a callback previously registered by [`Self::on_movement_tick`],
    /// causing it not to run in the future.
    fn remove_on_movement_tick(&self, callback: MovementTickCallbackId);
}

impl movement_tick for super::RemoteReducers {
    fn movement_tick(&self, timer: MovementTickTimer) -> __sdk::Result<()> {
        self.imp
            .call_reducer("movement_tick", MovementTickArgs { timer })
    }
    fn on_movement_tick(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &MovementTickTimer) + Send + 'static,
    ) -> MovementTickCallbackId {
        MovementTickCallbackId(self.imp.on_reducer(
            "movement_tick",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::MovementTick { timer },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, timer)
            }),
        ))
    }
    fn remove_on_movement_tick(&self, callback: MovementTickCallbackId) {
        self.imp.remove_on_reducer("movement_tick", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `movement_tick`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_movement_tick {
    /// Set the call-reducer flags for the reducer `movement_tick` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn movement_tick(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_movement_tick for super::SetReducerFlags {
    fn movement_tick(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("movement_tick", flags);
    }
}
