// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::race_type::Race;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `race`.
///
/// Obtain a handle from the [`RaceTableAccess::race`] method on [`super::RemoteTables`],
/// like `ctx.db.race()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.race().on_insert(...)`.
pub struct RaceTableHandle<'ctx> {
    imp: __sdk::TableHandle<Race>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `race`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RaceTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RaceTableHandle`], which mediates access to the table `race`.
    fn race(&self) -> RaceTableHandle<'_>;
}

impl RaceTableAccess for super::RemoteTables {
    fn race(&self) -> RaceTableHandle<'_> {
        RaceTableHandle {
            imp: self.imp.get_table::<Race>("race"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RaceInsertCallbackId(__sdk::CallbackId);
pub struct RaceDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RaceTableHandle<'ctx> {
    type Row = Race;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Race> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RaceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RaceInsertCallbackId {
        RaceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RaceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RaceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RaceDeleteCallbackId {
        RaceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RaceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Race>("race");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}
pub struct RaceUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RaceTableHandle<'ctx> {
    type UpdateCallbackId = RaceUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RaceUpdateCallbackId {
        RaceUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RaceUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Race>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Race>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `race`,
/// which allows point queries on the field of the same name
/// via the [`RaceIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.race().id().find(...)`.
pub struct RaceIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Race, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RaceTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `race`.
    pub fn id(&self) -> RaceIdUnique<'ctx> {
        RaceIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RaceIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Race> {
        self.imp.find(col_val)
    }
}

/// Access to the `name` unique index on the table `race`,
/// which allows point queries on the field of the same name
/// via the [`RaceNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.race().name().find(...)`.
pub struct RaceNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Race, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RaceTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `race`.
    pub fn name(&self) -> RaceNameUnique<'ctx> {
        RaceNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RaceNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Race> {
        self.imp.find(col_val)
    }
}
