// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::quat_type::Quat;
use super::transform_type::Transform;
use super::vec_3_type::Vec3;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `transform`.
///
/// Obtain a handle from the [`TransformTableAccess::transform`] method on [`super::RemoteTables`],
/// like `ctx.db.transform()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.transform().on_insert(...)`.
pub struct TransformTableHandle<'ctx> {
    imp: __sdk::TableHandle<Transform>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `transform`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TransformTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TransformTableHandle`], which mediates access to the table `transform`.
    fn transform(&self) -> TransformTableHandle<'_>;
}

impl TransformTableAccess for super::RemoteTables {
    fn transform(&self) -> TransformTableHandle<'_> {
        TransformTableHandle {
            imp: self.imp.get_table::<Transform>("transform"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TransformInsertCallbackId(__sdk::CallbackId);
pub struct TransformDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TransformTableHandle<'ctx> {
    type Row = Transform;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Transform> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TransformInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransformInsertCallbackId {
        TransformInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TransformInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TransformDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransformDeleteCallbackId {
        TransformDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TransformDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Transform>("transform");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct TransformUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TransformTableHandle<'ctx> {
    type UpdateCallbackId = TransformUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TransformUpdateCallbackId {
        TransformUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TransformUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Transform>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Transform>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `transform`,
/// which allows point queries on the field of the same name
/// via the [`TransformIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.transform().id().find(...)`.
pub struct TransformIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Transform, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TransformTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `transform`.
    pub fn id(&self) -> TransformIdUnique<'ctx> {
        TransformIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TransformIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Transform> {
        self.imp.find(col_val)
    }
}
