// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::xp_progression_type::XpProgression;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `xp_progression`.
///
/// Obtain a handle from the [`XpProgressionTableAccess::xp_progression`] method on [`super::RemoteTables`],
/// like `ctx.db.xp_progression()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.xp_progression().on_insert(...)`.
pub struct XpProgressionTableHandle<'ctx> {
    imp: __sdk::TableHandle<XpProgression>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `xp_progression`.
///
/// Implemented for [`super::RemoteTables`].
pub trait XpProgressionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`XpProgressionTableHandle`], which mediates access to the table `xp_progression`.
    fn xp_progression(&self) -> XpProgressionTableHandle<'_>;
}

impl XpProgressionTableAccess for super::RemoteTables {
    fn xp_progression(&self) -> XpProgressionTableHandle<'_> {
        XpProgressionTableHandle {
            imp: self.imp.get_table::<XpProgression>("xp_progression"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct XpProgressionInsertCallbackId(__sdk::CallbackId);
pub struct XpProgressionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for XpProgressionTableHandle<'ctx> {
    type Row = XpProgression;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = XpProgression> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = XpProgressionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> XpProgressionInsertCallbackId {
        XpProgressionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: XpProgressionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = XpProgressionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> XpProgressionDeleteCallbackId {
        XpProgressionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: XpProgressionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<XpProgression>("xp_progression");
    _table.add_unique_constraint::<u8>("level", |row| &row.level);
}
pub struct XpProgressionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for XpProgressionTableHandle<'ctx> {
    type UpdateCallbackId = XpProgressionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> XpProgressionUpdateCallbackId {
        XpProgressionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: XpProgressionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<XpProgression>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<XpProgression>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `level` unique index on the table `xp_progression`,
/// which allows point queries on the field of the same name
/// via the [`XpProgressionLevelUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.xp_progression().level().find(...)`.
pub struct XpProgressionLevelUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<XpProgression, u8>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> XpProgressionTableHandle<'ctx> {
    /// Get a handle on the `level` unique index on the table `xp_progression`.
    pub fn level(&self) -> XpProgressionLevelUnique<'ctx> {
        XpProgressionLevelUnique {
            imp: self.imp.get_unique_constraint::<u8>("level"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> XpProgressionLevelUnique<'ctx> {
    /// Find the subscribed row whose `level` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u8) -> Option<XpProgression> {
        self.imp.find(col_val)
    }
}
