// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::xp_type::Xp;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `xp`.
///
/// Obtain a handle from the [`XpTableAccess::xp`] method on [`super::RemoteTables`],
/// like `ctx.db.xp()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.xp().on_insert(...)`.
pub struct XpTableHandle<'ctx> {
    imp: __sdk::TableHandle<Xp>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `xp`.
///
/// Implemented for [`super::RemoteTables`].
pub trait XpTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`XpTableHandle`], which mediates access to the table `xp`.
    fn xp(&self) -> XpTableHandle<'_>;
}

impl XpTableAccess for super::RemoteTables {
    fn xp(&self) -> XpTableHandle<'_> {
        XpTableHandle {
            imp: self.imp.get_table::<Xp>("xp"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct XpInsertCallbackId(__sdk::CallbackId);
pub struct XpDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for XpTableHandle<'ctx> {
    type Row = Xp;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Xp> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = XpInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> XpInsertCallbackId {
        XpInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: XpInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = XpDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> XpDeleteCallbackId {
        XpDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: XpDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Xp>("xp");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct XpUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for XpTableHandle<'ctx> {
    type UpdateCallbackId = XpUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> XpUpdateCallbackId {
        XpUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: XpUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Xp>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Xp>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `xp`,
/// which allows point queries on the field of the same name
/// via the [`XpIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.xp().id().find(...)`.
pub struct XpIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Xp, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> XpTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `xp`.
    pub fn id(&self) -> XpIdUnique<'ctx> {
        XpIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> XpIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Xp> {
        self.imp.find(col_val)
    }
}
